# Generated by Django 6.1.1 on 2026-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_cost', models.IntegerField()),
                ('base_cost', models.IntegerField()),
                ('sell_price', models.IntegerField(default=0)),
                ('stats', models.JSONField(default=dict, help_text="e.g. {'attack_damage': 65, 'critical_strike_chance': 20}")),
            ],
        ),
    ]
