# Generated by Django 6.1.1 on 2026-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('lore', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
                ('spells', models.JSONField(default=list)),
                ('passive', models.JSONField(default=dict)),
            ],
        ),
    ]
