# Generated by Django 6.1.1 on 2026-10-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='riot_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='riot_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
