# Generated by Django 6.1.1 on 2026-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_champion_riot_id_item_riot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='image_file',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='image_file',
            field=models.CharField(default='', max_length=50),
        ),
    ]
