# Generated by Django 6.1.1 on 2026-10-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_champion_image_file_item_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
